/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.material;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;

import ti.modules.titanium.ui.android.AndroidModule;
import android.app.Activity;

@Kroll.proxy(creatableInModule=TiMaterialModule.class,
propertyAccessors = {
	TiC.PROPERTY_VALUE,
	TiC.PROPERTY_STYLE,
	TiC.PROPERTY_TITLE,
	TiC.PROPERTY_TITLE_ON,
	TiC.PROPERTY_TITLE_OFF,
	TiC.PROPERTY_COLOR,
	TiC.PROPERTY_FONT,
	TiC.PROPERTY_TEXT_ALIGN,
	TiC.PROPERTY_VERTICAL_ALIGN
})
public class SwitchProxy extends TiViewProxy
{
	public SwitchProxy()
	{
		super();
		defaultValues.put(TiC.PROPERTY_VALUE, false);
		defaultValues.put(TiC.PROPERTY_STYLE, AndroidModule.SWITCH_STYLE_SWITCH);
	}

	@Override
	public TiUIView createView(Activity activity)
	{
		return new SwitchView(this);
	}

	@Override
	public String getApiName()
	{
		return "Ti.UI.Switch";
	}
}
